version: '3'

services:
  openvpn:
    image: croc/openvpn
    environment:
#      - SERVER_ADDRESS=vpn.myvpn-domain.com
      - SERVER_PORT=51194
      - PROTO=udp
      - KEY_COUNTRY=HU
      - KEY_PROVINCE=HU
      - KEY_CITY=Budapest
      - KEY_ORG=My Tech Company
      - KEY_EMAIL=vpn@my-tech-company.com
      - KEY_OU=IT NETWORK
      - NAT_RULE_AUTO=false
#      - RADIUS_SERVER=127.0.0.1
#      - RADIUS_SECRET=secret
    volumes:
      - './openvpn/config:/etc/openvpn'
    network_mode: "host"
    privileged: true
    restart: always
